# Generated by Django 5.2.8 on 2025-11-28 06:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title/name of the task', max_length=200)),
                ('due_date', models.DateField(help_text='When the task is due')),
                ('estimated_hours', models.FloatField(help_text='Estimated time to complete the task in hours', validators=[django.core.validators.MinValueValidator(0.1)])),
                ('importance', models.IntegerField(help_text='Importance level from 1 (low) to 10 (high)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dependencies', models.ManyToManyField(blank=True, help_text='Tasks that must be completed before this task', related_name='dependents', to='tasks.task')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
